### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by capaj** [zabel-xyz/local-history#12]
lastest version on vscode 1.10.2, happens when an empty project is opened

```
Activating extension `xyz.local-history` failed:  Path must be a string. Received undefined
Here is the error stack:  TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at HistoryController.readSettings (/home/capaj/.vscode/extensions/xyz.local-history-1.1.0/out/src/history.controller.js:296:71)
    at new HistoryController (/home/capaj/.vscode/extensions/xyz.local-history-1.1.0/out/src/history.controller.js:14:30)
    at activate (/home/capaj/.vscode/extensions/xyz.local-history-1.1.0/out/src/extension.js:9:24)
    at Function.t._callActivateOptional (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:15:25830)
    at Function.t._callActivate (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:15:25615)
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:15:25390
    at Object.m [as _notify] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:6584)
    at Object.enter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:10162)
    at _run (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:11990)
    at _completed (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:11431)
    at c (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:14969)
    at n.Class.derive.join.i.forEach.J.then.o.(anonymous function) (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:15186)
    at Object.m [as _notify] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:6584)
    at Object.enter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:10162)
    at _run (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:11990)
    at _completed (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:11431)
    at c (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:14969)
    at n.Class.derive.join.i.forEach.J.then.o.(anonymous function) (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:15186)
    at Object.m [as _notify] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:6584)
    at Object.enter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:10162)
```

**Comment by zabel-xyz** [comment]
Try with last version 1.1.1
