### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined 

### ISSUE THREAD

**Issue by jrieken** [zabel-xyz/local-history#2]
```
TypeError: Cannot read property 'length' of undefined 
at \xyz.local-history-0.0.4\out\src\extension.js:45:23 
at Object.p [as _notify] (\out\vs\workbench\node\pluginHostProcess.js:5:12448) 
at Object.__dirname.undefined.L.enter (\out\vs\workbench\node\pluginHostProcess.js:5:15610) 
at __dirname.undefined.t.Class.define._run (\out\vs\workbench\node\pluginHostProcess.js:5:17436) 
at __dirname.undefined.t.Class.define._completed (\out\vs\workbench\node\pluginHostProcess.js:5:16877) 
at h (\out\vs\workbench\node\pluginHostProcess.js:11:16675) 
at doNTCallback0 (node.js:420:9) 
at process._tickCallback (node.js:349:13) 
```

**Comment by zabel-xyz** [comment]
I make a small correction to avoid this error.
It seem that findFiles return nothing when you try to save your file, but I don't know if this is ok with so little information.

**Comment by jrieken** [comment]
> It seem that findFiles return nothing when you try to save your file

Unsure what you mean by that. Is that searching for unsaved files?

**Comment by zabel-xyz** [comment]
No, I use workspace.findFiles to avoid certain files to be saved in history 
(cf. settings/local-history.exclude)

`workspace.findFiles(fileToSave, excludeFilter) .then(files => {`
And files is undefined in your case !?

**Comment by zabel-xyz** [comment]
I have changed a lot of code since May (and VSCode too), so I close this issue...
