### ISSUE TITLE
Activating extension `xyz.local-history` failed:  Cannot find module 'wrappy'

### ISSUE THREAD

**Issue by alanaasmaa** [zabel-xyz/local-history#33]
I don't know whats happening but after last update many of my VsCode extensions stopped working. 

```
[Extension Host] Here is the error stack:  Error: Cannot find module 'wrappy'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.J.X.t.getExtensionPathIndex.then.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:490:709)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\AlanAasmaa\.vscode\extensions\xyz.local-history-1.6.2\node_modules\inflight\inflight.js:1:169)
	at Object.<anonymous> (C:\Users\AlanAasmaa\.vscode\extensions\xyz.local-history-1.6.2\node_modules\inflight\inflight.js:56:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.J.X.t.getExtensionPathIndex.then.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:490:709)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\AlanAasmaa\.vscode\extensions\xyz.local-history-1.6.2\node_modules\glob\glob.js:58:16)
```

**Comment by zabel-xyz** [comment]
Always this error ?

**Comment by alanaasmaa** [comment]
Actually it works now. Its 3 months old error i have no idea what i did.
